In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])

In [3]:
b = np.array([4, 5, 6])

In [4]:
np.r_[a, b]

array([1, 2, 3, 4, 5, 6])

In [5]:
np.r_[2, 5, 3, np.array([2, 3]), 4.2]

array([2. , 5. , 3. , 2. , 3. , 4.2])

In [6]:
c = np.zeros((2, 3))

In [8]:
d = np.ones((3, 3))

In [9]:
np.r_[c, d]

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
d = np.ones((3, 4))

In [11]:
np.r_[c, d]

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 4

In [12]:
a = np.ones((2, 2))

In [13]:
b = np.zeros((2, 2))

In [14]:
np.r_["1", a, b]

array([[1., 1., 0., 0.],
       [1., 1., 0., 0.]])

In [16]:
np.r_["1", a, b].shape

(2, 4)

In [17]:
np.r_["0", a, b]

array([[1., 1.],
       [1., 1.],
       [0., 0.],
       [0., 0.]])

In [18]:
np.r_["0", a, b].shape

(4, 2)

In [19]:
np.r_[a, b].shape

(4, 2)

In [20]:
c = np.ones((2, 2, 2))

In [21]:
d = np.zeros((2, 2, 2))

In [22]:
c

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [23]:
d

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [24]:
np.r_["0", c, d]

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [25]:
np.r_["1", c, d]

array([[[1., 1.],
        [1., 1.],
        [0., 0.],
        [0., 0.]],

       [[1., 1.],
        [1., 1.],
        [0., 0.],
        [0., 0.]]])

In [26]:
np.r_["2", c, d]

array([[[1., 1., 0., 0.],
        [1., 1., 0., 0.]],

       [[1., 1., 0., 0.],
        [1., 1., 0., 0.]]])

In [27]:
np.r_["0", c, d].shape

(4, 2, 2)

In [28]:
np.r_["1", c, d].shape

(2, 4, 2)

In [29]:
np.r_["2", c, d].shape

(2, 2, 4)

In [30]:
np.r_["0, 2", [0, 1, 2], [3, 3, 3]]

array([[0, 1, 2],
       [3, 3, 3]])

In [33]:
np.r_["0, 2", [0, 1, 2], [3, 3, 3]].shape

(2, 3)

In [34]:
np.r_["0, 3", [0, 1, 2], [3, 3, 3]]

array([[[0, 1, 2]],

       [[3, 3, 3]]])

In [35]:
np.r_["0, 3", [0, 1, 2], [3, 3, 3]].shape

(2, 1, 3)

In [36]:
np.r_["0, 2, -1", [0, 1, 2], [3, 3, 3]]

array([[0, 1, 2],
       [3, 3, 3]])

In [37]:
np.r_["0, 2, -1", [0, 1, 2], [3, 3, 3]].shape

(2, 3)

In [38]:
np.r_["0, 2, 0", [0, 1, 2], [3, 3, 3]]

array([[0],
       [1],
       [2],
       [3],
       [3],
       [3]])

In [41]:
np.r_["0, 2, 0", [0, 1, 2], [3, 3, 3]].shape

(6, 1)

In [42]:
np.r_["0, 3, 0", [0, 1, 2], [3, 3, 3]]

array([[[0]],

       [[1]],

       [[2]],

       [[3]],

       [[3]],

       [[3]]])

In [43]:
np.r_["0, 3, 0", [0, 1, 2], [3, 3, 3]].shape

(6, 1, 1)

In [46]:
np.r_[0:10, 0:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
np.r_[:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
np.r_[0:10:2]

array([0, 2, 4, 6, 8])

In [50]:
np.r_[10:0:-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [51]:
np.r_[0:10, 0, 4, np.array([3, 3])]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 4, 3, 3])

In [52]:
a = np.array([1, 4, 6])

In [54]:
b = np.array([2, 2, 2])

In [60]:
np.r_["r", a, b]

matrix([[1, 4, 6, 2, 2, 2]])

In [58]:
np.r_["c", a, b]

matrix([[1],
        [4],
        [6],
        [2],
        [2],
        [2]])

In [61]:
c = np.ones((4, 5))

In [62]:
d = np.zeros((2, 5))

In [63]:
np.r_["r", c, d]

matrix([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [64]:
np.r_["c", c, d]

matrix([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [65]:
a = np.ones((3, 2))

In [66]:
b = np.zeros((3, 3))

In [67]:
a

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [68]:
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [69]:
np.c_[a, b]

array([[1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.]])

In [70]:
c = np.zeros(3)

In [71]:
np.c_[a, c]

array([[1., 1., 0.],
       [1., 1., 0.],
       [1., 1., 0.]])

In [73]:
np.c_[a, c].shape

(3, 3)

In [74]:
a = np.random.randn(1200 * 1000).reshape(1200, -1)

In [75]:
np.save("a", a)

In [76]:
np.load("a.npy")

array([[-0.69779469, -0.86109287,  0.37256334, ..., -0.88036462,
         0.61136712, -1.56962378],
       [-0.04161808, -0.37253419, -0.84091332, ...,  0.02412578,
        -0.67546294,  0.79060322],
       [-0.18873623, -0.43877077, -1.09782279, ..., -0.18238653,
        -0.6997955 , -1.48040915],
       ...,
       [-1.88269416,  0.82347365, -0.17397532, ..., -0.94566963,
        -0.16917957,  1.11163337],
       [-0.9572196 ,  0.34102369,  0.01699212, ...,  1.88465459,
        -0.10233889,  1.71076658],
       [ 0.37768663, -0.45106938, -1.35188478, ..., -1.05729885,
         0.12665351,  0.78604199]])

In [77]:
c = np.random.randn(12 * 20 * 40).reshape(12, 20, 40)

In [78]:
np.save("c", c)

In [79]:
d = np.load("c.npy")

In [80]:
d.shape

(12, 20, 40)

In [81]:
a = np.random.randn(3, 4)

In [82]:
np.savetxt("sample.txt", a)

In [83]:
b = np.loadtxt("sample.txt")

In [84]:
a

array([[-0.83748117,  0.79881687, -0.24656905,  0.26125006],
       [ 1.99194506,  0.06959999, -1.56438867, -0.07841481],
       [-0.45376036,  1.25896247, -0.9691473 , -0.89328229]])

In [85]:
b

array([[-0.83748117,  0.79881687, -0.24656905,  0.26125006],
       [ 1.99194506,  0.06959999, -1.56438867, -0.07841481],
       [-0.45376036,  1.25896247, -0.9691473 , -0.89328229]])

In [86]:
np.savetxt("sample.csv", a)

In [87]:
c = np.loadtxt("sample.csv")

In [88]:
c

array([[-0.83748117,  0.79881687, -0.24656905,  0.26125006],
       [ 1.99194506,  0.06959999, -1.56438867, -0.07841481],
       [-0.45376036,  1.25896247, -0.9691473 , -0.89328229]])

In [90]:
np.savetxt("sample2.txt", a, delimiter = ",")

In [91]:
e = np.loadtxt("sample2.txt")

ValueError: could not convert string to float: '-8.374811678743432353e-01,7.988168672085838029e-01,-2.465690462764510149e-01,2.612500624351667411e-01'

In [92]:
e = np.loadtxt("sample2.txt", delimiter = ",")

In [93]:
e

array([[-0.83748117,  0.79881687, -0.24656905,  0.26125006],
       [ 1.99194506,  0.06959999, -1.56438867, -0.07841481],
       [-0.45376036,  1.25896247, -0.9691473 , -0.89328229]])

In [94]:
np.savetxt("sample3.txt", a, fmt = "%.2e")

In [95]:
np.savetxt("sample4.txt", a, fmt = "%.2f")

In [98]:
np.savetxt("sample5.txt", a, fmt = "%.3e", header = "this is a header", footer = "this is a footer")

In [99]:
np.savetxt("sample6.txt", a, fmt = "%.3e", header = "this is a header", footer = "this is a footer", comments = ">>>")

In [100]:
np.loadtxt("sample6.txt", comments = ">>>")

array([[-0.8375 ,  0.7988 , -0.2466 ,  0.2613 ],
       [ 1.992  ,  0.0696 , -1.564  , -0.07841],
       [-0.4538 ,  1.259  , -0.9691 , -0.8933 ]])

In [101]:
np.loadtxt("sample4.txt", usecols = (0, 2))

array([[-0.84, -0.25],
       [ 1.99, -1.56],
       [-0.45, -0.97]])

In [103]:
np.loadtxt("sample4.txt", skiprows = 1)

array([[ 1.99,  0.07, -1.56, -0.08],
       [-0.45,  1.26, -0.97, -0.89]])

In [106]:
np.loadtxt("foo.csv", dtype = [("col1", "i8"), ("col2", "S10"), ("col3", "f8"), ("col4", "S10")])

array([(18, b'female', 154.1, b'No'), (21, b'male', 172.3, b'Yes'),
       (22, b'female', 160.8, b'Yes'), (23, b'male', 180.1, b'Yes'),
       (25, b'female', 145. , b'No')],
      dtype=[('col1', '<i8'), ('col2', 'S10'), ('col3', '<f8'), ('col4', 'S10')])

In [107]:
np.loadtxt("foo.csv", dtype = [("col1", "i8"), ("col2", "S10"), ("col3", "f8"), ("col4", "S10")], unpack = True)

[array([18, 21, 22, 23, 25], dtype=int64),
 array([b'female', b'male', b'female', b'male', b'female'], dtype='|S10'),
 array([154.1, 172.3, 160.8, 180.1, 145. ]),
 array([b'No', b'Yes', b'Yes', b'Yes', b'No'], dtype='|S10')]

In [108]:
age, gender, tall, driver_license = np.loadtxt("foo.csv", dtype = [("col1", "i8"), ("col2", "S10"), ("col3", "f8"), ("col4", "S10")], unpack = True)

In [109]:
age

array([18, 21, 22, 23, 25], dtype=int64)

In [110]:
gender

array([b'female', b'male', b'female', b'male', b'female'], dtype='|S10')

In [111]:
tall

array([154.1, 172.3, 160.8, 180.1, 145. ])

In [112]:
driver_license

array([b'No', b'Yes', b'Yes', b'Yes', b'No'], dtype='|S10')

In [114]:
def driver_license(str):
    if str == b"Yes": return 1
    else: return -1

In [115]:
def gender(str):
    if str == b"male": return 1
    else: return -1

In [116]:
np.loadtxt("foo.csv", converters = {1:gender, 3:driver_license})

array([[ 18. ,  -1. , 154.1,  -1. ],
       [ 21. ,   1. , 172.3,   1. ],
       [ 22. ,  -1. , 160.8,   1. ],
       [ 23. ,   1. , 180.1,   1. ],
       [ 25. ,  -1. , 145. ,  -1. ]])

In [117]:
np.random.rand()

0.9675045842647497

In [118]:
np.random.randint(10)

4

In [119]:
np.random.rand(2, 3)

array([[0.5477751 , 0.45711815, 0.12704176],
       [0.61327852, 0.02288831, 0.32635937]])

In [120]:
np.random.randint(10, size = (2, 3))

array([[2, 7, 3],
       [1, 4, 9]])

In [121]:
np.random.randint(5, 10, size = 10)

array([6, 7, 9, 8, 7, 7, 8, 8, 6, 6])

In [122]:
(10 - 5) * np.random.rand(10) + 5

array([8.26696558, 5.3504221 , 6.85603441, 6.7356786 , 7.49092601,
       9.52706074, 7.10043698, 5.55154152, 7.10994967, 7.72909193])

In [138]:
np.random.seed(21)

In [143]:
np.random.rand()

0.20592276526743902

In [144]:
np.random.rand()

0.0507732566953768

In [145]:
np.random.seed(10)

In [146]:
np.random.rand(20)

array([0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701,
       0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981,
       0.68535982, 0.95339335, 0.00394827, 0.51219226, 0.81262096,
       0.61252607, 0.72175532, 0.29187607, 0.91777412, 0.71457578])

In [147]:
np.random.seed(23)

In [148]:
np.random.rand(20)

array([0.51729788, 0.9469626 , 0.76545976, 0.28239584, 0.22104536,
       0.68622209, 0.1671392 , 0.39244247, 0.61805235, 0.41193009,
       0.00246488, 0.88403218, 0.88494754, 0.30040969, 0.58958187,
       0.97842692, 0.84509382, 0.06507544, 0.29474446, 0.28793444])

In [149]:
np.random.seed(10)

In [150]:
np.random.rand(20)

array([0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701,
       0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981,
       0.68535982, 0.95339335, 0.00394827, 0.51219226, 0.81262096,
       0.61252607, 0.72175532, 0.29187607, 0.91777412, 0.71457578])

In [151]:
np.random.seed(23)

In [152]:
np.random.rand(20)

array([0.51729788, 0.9469626 , 0.76545976, 0.28239584, 0.22104536,
       0.68622209, 0.1671392 , 0.39244247, 0.61805235, 0.41193009,
       0.00246488, 0.88403218, 0.88494754, 0.30040969, 0.58958187,
       0.97842692, 0.84509382, 0.06507544, 0.29474446, 0.28793444])

In [153]:
a = ["Python", "Ruby", "Java", "JavaScript", "PHP"]

In [156]:
np.random.choice(a, 3)

array(['PHP', 'Java', 'Ruby'], dtype='<U10')

In [163]:
np.random.choice(a, 5, replace = False).size

5

In [167]:
a = np.random.choice(a, 20, p = [0.8, 0.05, 0.05, 0.05, 0.05])

In [174]:
np.where(a == "Python")[0].size / 20

0.7

In [176]:
np.random.choice(5, 10)

array([0, 0, 2, 2, 2, 2, 0, 1, 1, 0])

In [177]:
a = np.arange(10)

In [178]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [179]:
np.random.shuffle(a)

In [180]:
a

array([0, 8, 5, 1, 3, 2, 9, 7, 4, 6])

In [181]:
a

array([0, 8, 5, 1, 3, 2, 9, 7, 4, 6])