In [2]:
import numpy as np

In [3]:
a = np.array([[1, 1, 1], [1, 0, 1], [1, 0, 1]])

In [4]:
np.all(a)

False

In [5]:
b = np.ones((3, 3))

In [6]:
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
b.dtype

dtype('float64')

In [8]:
np.all(b)

True

In [9]:
np.all(a < 2)

True

In [10]:
np.all(b % 3 < 2)

True

In [11]:
np.all(a, axis = 0)

array([ True, False,  True])

In [12]:
np.all(a, axis = 1)

array([ True, False, False])

In [13]:
np.all(a, axis = 0, keepdims = True).shape

(1, 3)

In [14]:
a.all()

False

In [15]:
b.all()

True

In [16]:
a.all(axis = 1)

array([ True, False, False])

In [17]:
(a < 2).all()

True

In [18]:
a < 2

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [19]:
a.all(keepdims = True)

array([[False]])

In [20]:
a = np.random.randint(10, size = (2, 3))

In [21]:
a

array([[8, 3, 3],
       [6, 1, 0]])

In [22]:
np.any(a == 9)

False

In [23]:
np.any(a == 0)

True

In [24]:
np.any(a % 2 ==0, axis = 0)

array([ True, False,  True])

In [25]:
np.any(a % 2 == 1, axis = 1)

array([ True,  True])

In [26]:
np.any(a % 2 == 1, axis = 1, keepdims = True)

array([[ True],
       [ True]])

In [27]:
(a % 5 == 0).any()

True

In [28]:
(a > 3).any()

True

In [29]:
b = np.random.randint(10, size = (2, 3))

In [30]:
a

array([[8, 3, 3],
       [6, 1, 0]])

In [31]:
b

array([[0, 1, 1],
       [5, 4, 1]])

In [32]:
(a == b).any(axis = 1)

array([False, False])

In [33]:
(a == b).any(axis = 1, keepdims = True)

array([[False],
       [False]])

In [34]:
c = np.random.randint(10, size = (2, 2))

In [35]:
c

array([[2, 0],
       [8, 5]])

In [36]:
(a == b).any(axis = 1)

array([False, False])

In [37]:
(a == c).any(axis = 1)

<ipython-input-37-385ede813949>:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  (a == c).any(axis = 1)


AttributeError: 'bool' object has no attribute 'any'

In [38]:
np.any(a == c, axis = 1)

<ipython-input-38-32a8ed9d239b>:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  np.any(a == c, axis = 1)


AxisError: axis 1 is out of bounds for array of dimension 0

In [39]:
a = np.arange(20, 0, -2)

In [40]:
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [41]:
np.where(a < 10)

(array([6, 7, 8, 9], dtype=int64),)

In [42]:
a[(0, 1, 2, 3)]

IndexError: too many indices for array: array is 1-dimensional, but 4 were indexed

In [43]:
a[0]

20

In [44]:
a[(2,)]

16

In [45]:
a[np.where(a < 10)]

array([8, 6, 4, 2])

In [46]:
a = np.arange(12).reshape((3, 4))

In [47]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [48]:
np.where(a % 2 == 0)

(array([0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 2, 0, 2, 0, 2], dtype=int64))

In [49]:
a[np.where(a % 2 == 0)]

array([ 0,  2,  4,  6,  8, 10])

In [51]:
np.where(a % 2 == 0, "even", "odd")

array([['even', 'odd', 'even', 'odd'],
       ['even', 'odd', 'even', 'odd'],
       ['even', 'odd', 'even', 'odd']], dtype='<U4')

In [52]:
np.where(a % 2 == 0, "even")

ValueError: either both or neither of x and y should be given

In [53]:
b = np.reshape(a, (3, 4))

In [54]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [55]:
c = b ** 2

In [56]:
c

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]], dtype=int32)

In [57]:
np.where(b % 2 == 0, b, b ** 2)

array([[  0,   1,   2,   9],
       [  4,  25,   6,  49],
       [  8,  81,  10, 121]])

In [58]:
np.max(np.array([1, 2, 3, 2, 1]))

3

In [59]:
arr = np.array([1, 2, 3, 4]).reshape((2, 2))

In [60]:
arr

array([[1, 2],
       [3, 4]])

In [61]:
np.amax(arr, axis = 0)

array([3, 4])

In [62]:
np.amax(arr, axis = 1)

array([2, 4])

In [63]:
np.amax(arr, keepdims = True)

array([[4]])

In [64]:
b = np.random.randint(30, size = (2, 3, 5))

In [65]:
b

array([[[29,  9,  6, 29, 10],
        [ 6,  6, 11, 19, 27],
        [24,  0,  2, 12,  8]],

       [[10, 13, 26, 18, 10],
        [23,  6, 27,  6, 17],
        [ 9, 22,  1, 17,  6]]])

In [66]:
b.amx(axis = 0)

AttributeError: 'numpy.ndarray' object has no attribute 'amx'

In [67]:
b.amax(axis = 0)

AttributeError: 'numpy.ndarray' object has no attribute 'amax'

In [68]:
b.max(axis = 0)

array([[29, 13, 26, 29, 10],
       [23,  6, 27, 19, 27],
       [24, 22,  2, 17,  8]])

In [69]:
b.max(axis = 1)

array([[29,  9, 11, 29, 27],
       [23, 22, 27, 18, 17]])

In [70]:
b.max(axis = 2)

array([[29, 27, 24],
       [26, 27, 22]])

In [71]:
a = np.array([[1.2, 1.3, 0.1, 1.5], [2.1, 0.2, 0.3, 2.0], [0.1, 0.5, 0.5, 2.3]])

In [72]:
np.amin(a)

0.1

In [73]:
np.amin(a, axis = 0)

array([0.1, 0.2, 0.1, 1.5])

In [74]:
np.amin(a, axis = 1)

array([0.1, 0.2, 0.1])

In [75]:
np.amin(a, axis = 0, keepdims = True)

array([[0.1, 0.2, 0.1, 1.5]])

In [76]:
np.amin(a, axis = 1, keepdims = True)

array([[0.1],
       [0.2],
       [0.1]])

In [77]:
a = np.random.randint(10, size = 10)

In [78]:
a

array([9, 4, 7, 8, 8, 5, 5, 0, 4, 4])

In [79]:
np.argmax(a)

0

In [80]:
a.argmax()

0

In [81]:
b = np.random.randint(10, size = (3, 4))

In [82]:
b

array([[9, 1, 6, 5],
       [3, 2, 9, 7],
       [6, 8, 6, 1]])

In [83]:
np.argmax(b)

0

In [84]:
b

array([[9, 1, 6, 5],
       [3, 2, 9, 7],
       [6, 8, 6, 1]])

In [85]:
np.argmax(b, axis = 0)

array([0, 2, 1, 1], dtype=int64)

In [86]:
np.argmax(b, axis = 1)

array([0, 2, 1], dtype=int64)

In [87]:
c = np.random.randint(10, size = (2, 3, 4))

In [88]:
c

array([[[2, 1, 2, 5],
        [9, 6, 0, 2],
        [1, 2, 5, 6]],

       [[3, 1, 3, 4],
        [7, 6, 8, 5],
        [4, 6, 7, 8]]])

In [89]:
np.armax(c, axis = 0)

AttributeError: module 'numpy' has no attribute 'armax'

In [90]:
np.argmax(c, axis = 0)

array([[1, 0, 1, 0],
       [0, 0, 1, 1],
       [1, 1, 1, 1]], dtype=int64)

In [91]:
np.argmax(c, axis = 1)

array([[1, 1, 2, 2],
       [1, 1, 1, 2]], dtype=int64)

In [92]:
np.argmax(c, axis = 2)

array([[3, 0, 3],
       [3, 2, 3]], dtype=int64)

In [93]:
np.argmax(c, axis = 1, keepdims = True)

TypeError: _argmax_dispatcher() got an unexpected keyword argument 'keepdims'

In [94]:
d = np.array([1.2, 1.5, 2.3, 1.8], [0.2, 2.5, 2.1, 2.0], [3.1, 3.3, 1.5, 2.1])

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [95]:
d = np.array([[1.2, 1.5, 2.3, 1.8], [0.2, 2.5, 2.1, 2.0], [3.1, 3.3, 1.5, 2.1]])

In [96]:
d

array([[1.2, 1.5, 2.3, 1.8],
       [0.2, 2.5, 2.1, 2. ],
       [3.1, 3.3, 1.5, 2.1]])

In [97]:
np.argmin(d)

4

In [98]:
np.argmin(d, axis =0 )

array([1, 0, 2, 0], dtype=int64)

In [99]:
np.argmin(d, axis = 1)

array([0, 0, 2], dtype=int64)

In [100]:
a = np.arange(12).reshape(3, 4)

In [101]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [102]:
np.transpose(a)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [103]:
np.tanspose(a, (1, 0))

AttributeError: module 'numpy' has no attribute 'tanspose'

In [104]:
np.transpose(a, (1, 0))

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [105]:
b = np.arange(6)

In [106]:
b

array([0, 1, 2, 3, 4, 5])

In [107]:
np.transpose(b)

array([0, 1, 2, 3, 4, 5])

In [108]:
b.shape

(6,)

In [111]:
b = b.reshape((1, -1))

In [112]:
np.transpose(b)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])