In [1]:
import numpy as np

In [2]:
c = np.arange(24).reshape(4, 3, 2)

In [3]:
c

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [4]:
c.shape

(4, 3, 2)

In [5]:
c.transpose((1, 0, 2))

array([[[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19]],

       [[ 2,  3],
        [ 8,  9],
        [14, 15],
        [20, 21]],

       [[ 4,  5],
        [10, 11],
        [16, 17],
        [22, 23]]])

In [6]:
c.transpose((1, 0, 2)).shape

(3, 4, 2)

In [7]:
np.transpose((1, 0, 2)).shape

(3,)

In [8]:
np.transpose(c, (1, 0, 2)).shape

(3, 4, 2)

In [9]:
a = np.arange(12).reshape(3, 4)

In [10]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [11]:
a.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [12]:
b = np.array([[0, 1, 2, 3, 4, 5]])

In [13]:
b

array([[0, 1, 2, 3, 4, 5]])

In [14]:
b.T

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [15]:
c

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [16]:
c.T

array([[[ 0,  6, 12, 18],
        [ 2,  8, 14, 20],
        [ 4, 10, 16, 22]],

       [[ 1,  7, 13, 19],
        [ 3,  9, 15, 21],
        [ 5, 11, 17, 23]]])

In [17]:
a.transpose().shape == a.T.shape

True

In [18]:
b.transpose().shape == b.T.shape

True

In [19]:
c.transpose().shape == c.T.shape

True

In [20]:
a = np.random.randint(0, 100, size = 20)

In [21]:
a

array([82, 84, 74, 29,  7, 77, 68, 82, 41, 13, 30, 97, 38, 46, 61, 38, 44,
       96, 85, 72])

In [22]:
np.sort(a)

array([ 7, 13, 29, 30, 38, 38, 41, 44, 46, 61, 68, 72, 74, 77, 82, 82, 84,
       85, 96, 97])

In [23]:
a = np.array([1, 3, 2])

In [24]:
np.argsort(a)

array([0, 2, 1], dtype=int64)

In [25]:
b = np.random.randint(0, 100, size = 20).reshape(4, 5)

In [26]:
b

array([[82,  6, 90, 56, 47],
       [ 7, 96, 11, 39, 67],
       [72, 38, 65, 65, 10],
       [64, 38,  9, 43,  0]])

In [27]:
np.sort(b)

array([[ 6, 47, 56, 82, 90],
       [ 7, 11, 39, 67, 96],
       [10, 38, 65, 65, 72],
       [ 0,  9, 38, 43, 64]])

In [28]:
np.argsort(b)

array([[1, 4, 3, 0, 2],
       [0, 2, 3, 4, 1],
       [4, 1, 2, 3, 0],
       [4, 2, 1, 3, 0]], dtype=int64)

In [29]:
np.sort(b, axis = 0)

array([[ 7,  6,  9, 39,  0],
       [64, 38, 11, 43, 10],
       [72, 38, 65, 56, 47],
       [82, 96, 90, 65, 67]])

In [30]:
np.argsort(b, axis = 0)

array([[1, 0, 3, 1, 3],
       [3, 2, 1, 3, 2],
       [2, 3, 2, 0, 0],
       [0, 1, 0, 2, 1]], dtype=int64)

In [31]:
c = np.random.randint(0, 100, size = (2, 4, 5))

In [32]:
c

array([[[41, 15,  8, 71,  8],
        [ 6, 14,  0, 42, 24],
        [39,  1,  6, 69, 74],
        [15, 46, 65, 16, 67]],

       [[89, 92, 27, 56, 15],
        [47, 97, 68, 45, 12],
        [25, 25, 26, 47, 57],
        [85, 56, 52, 19,  0]]])

In [33]:
np.sort(c, axis = 0)

array([[[41, 15,  8, 56,  8],
        [ 6, 14,  0, 42, 12],
        [25,  1,  6, 47, 57],
        [15, 46, 52, 16,  0]],

       [[89, 92, 27, 71, 15],
        [47, 97, 68, 45, 24],
        [39, 25, 26, 69, 74],
        [85, 56, 65, 19, 67]]])

In [34]:
np.argsort(c, axis = 0)

array([[[0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1],
        [1, 0, 0, 1, 1],
        [0, 0, 1, 0, 1]],

       [[1, 1, 1, 0, 1],
        [1, 1, 1, 1, 0],
        [0, 1, 1, 0, 0],
        [1, 1, 0, 1, 0]]], dtype=int64)

In [35]:
values = [("Alice", 25, 9.7), ("Bob", 12, 7.6), ("Catherine", 1, 8.6), ("David", 18, 7.6)]

In [36]:
dt = [("name", "S10"), ("ID", int), ("score", float)]

In [37]:
a = np.array(values, dtype = dt)

In [38]:
a

array([(b'Alice', 25, 9.7), (b'Bob', 12, 7.6), (b'Catherine',  1, 8.6),
       (b'David', 18, 7.6)],
      dtype=[('name', 'S10'), ('ID', '<i4'), ('score', '<f8')])

In [39]:
np.sort(a, order = "score")

array([(b'Bob', 12, 7.6), (b'David', 18, 7.6), (b'Catherine',  1, 8.6),
       (b'Alice', 25, 9.7)],
      dtype=[('name', 'S10'), ('ID', '<i4'), ('score', '<f8')])

In [40]:
np.argsort(a, order = "score")

array([1, 3, 2, 0], dtype=int64)

In [41]:
np.sort(a, order = ["score", "ID"])

array([(b'Bob', 12, 7.6), (b'David', 18, 7.6), (b'Catherine',  1, 8.6),
       (b'Alice', 25, 9.7)],
      dtype=[('name', 'S10'), ('ID', '<i4'), ('score', '<f8')])

In [42]:
a = np.random.randint(0, 100, 20)

In [43]:
a

array([46, 93, 12, 77, 49, 91, 53,  8, 87, 10, 68, 75,  3, 70, 71, 61, 34,
       68,  8, 79])

In [44]:
np.sort(a)

array([ 3,  8,  8, 10, 12, 34, 46, 49, 53, 61, 68, 68, 70, 71, 75, 77, 79,
       87, 91, 93])

In [45]:
a

array([46, 93, 12, 77, 49, 91, 53,  8, 87, 10, 68, 75,  3, 70, 71, 61, 34,
       68,  8, 79])

In [46]:
a.sort()

In [47]:
a

array([ 3,  8,  8, 10, 12, 34, 46, 49, 53, 61, 68, 68, 70, 71, 75, 77, 79,
       87, 91, 93])

In [48]:
a = np.arange(12)

In [49]:
b = np.arange(22)

In [50]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [51]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21])

In [52]:
np.hstack((a, b))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  0,  1,  2,  3,  4,
        5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [53]:
np.hstack((b, a))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [54]:
c = np.arange(4).reshape(2, 2)

In [55]:
c

array([[0, 1],
       [2, 3]])

In [56]:
np.hstack((a, c))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [57]:
d = np.arange(6).reshape(2, 3)

In [58]:
d

array([[0, 1, 2],
       [3, 4, 5]])

In [59]:
np.hstack((c, d))

array([[0, 1, 0, 1, 2],
       [2, 3, 3, 4, 5]])

In [60]:
e = np.arange(12).reshape(2, 2, 3)

In [61]:
f = np.arange(6).reshape(2, 1, 3)

In [62]:
e

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [63]:
e

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [64]:
f

array([[[0, 1, 2]],

       [[3, 4, 5]]])

In [65]:
np.hstack((e, f))

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 0,  1,  2]],

       [[ 6,  7,  8],
        [ 9, 10, 11],
        [ 3,  4,  5]]])

In [66]:
a = np.arange(12).reshape(-1, 1)

In [67]:
b = np.arange(2).reshape(-1, 1)

In [68]:
a

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [69]:
b

array([[0],
       [1]])

In [70]:
np.vstack((a, b))

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [ 0],
       [ 1]])

In [71]:
c = np.arange(2).reshape(1, 2)

In [72]:
c

array([[0, 1]])

In [73]:
np.vstack((a, c))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 1 and the array at index 1 has size 2

In [74]:
d = np.arange(4).reshape(2, 2)

In [75]:
c

array([[0, 1]])

In [76]:
d

array([[0, 1],
       [2, 3]])

In [77]:
np.vstack((c, d))

array([[0, 1],
       [0, 1],
       [2, 3]])

In [78]:
e = np.arange(24).reshape(4, 3, 2)

In [79]:
f = np.arange(6).reshape(1, 3, 2)

In [80]:
e

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [81]:
f

array([[[0, 1],
        [2, 3],
        [4, 5]]])

In [82]:
g = np.vstack((e, f))

In [83]:
g

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]],

       [[ 0,  1],
        [ 2,  3],
        [ 4,  5]]])

In [84]:
g.shape

(5, 3, 2)

In [85]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [87]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [89]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [90]:
a

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [91]:
b = np.zeros(a.shape)

In [92]:
b

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [93]:
b = np.zeros_like(a)

In [94]:
b

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0]])

In [96]:
np.ones(3)

array([1., 1., 1.])

In [97]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [101]:
a = np.ones(4, dtype = int)

In [100]:
np.ones(4, dtype = np.int8)

array([1, 1, 1, 1], dtype=int8)

In [102]:
a.dtype

dtype('int32')

In [103]:
a = np.array([[1, 2, 3], [2, 3, 4]])

In [104]:
np.ones_like(a)

array([[1, 1, 1],
       [1, 1, 1]])

In [107]:
b = np.array([2, 3, 4], dtype = np.int8)

In [108]:
np.ones_like(b)

array([1, 1, 1], dtype=int8)

In [110]:
np.empty(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [112]:
np.empty((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [114]:
%timeit np.zeros(10000)

2.03 µs ± 5.16 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [115]:
%timeit np.zeros(10000)

2.04 µs ± 4.06 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [116]:
%timeit np.ones(10000)

2.79 µs ± 6.01 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [118]:
%timeit np.empty(10000)

724 ns ± 3.78 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [119]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [120]:
np.arange(-10)

array([], dtype=int32)

In [121]:
np.arange(4.5)

array([0., 1., 2., 3., 4.])

In [122]:
np.arange(1, 8)

array([1, 2, 3, 4, 5, 6, 7])

In [123]:
np.arange(2, 10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [124]:
np.arange(0.5, 5.5)

array([0.5, 1.5, 2.5, 3.5, 4.5])

In [125]:
np.arange(0.55, 5.55)

array([0.55, 1.55, 2.55, 3.55, 4.55])

In [126]:
np.arange(2, 12, 2)

array([ 2,  4,  6,  8, 10])

In [127]:
np.arange(2, 5, 0.2)

array([2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4,
       4.6, 4.8])

In [128]:
np.arange(5, 2, -1)

array([5, 4, 3])

In [129]:
np.arange(2, 5, -1)

array([], dtype=int32)

In [130]:
np.arange(5, 2, 1)

array([], dtype=int32)

In [132]:
np.arange(stop = 3, step = 1)

TypeError: arange() missing required argument 'start' (pos 1)

In [133]:
np.arange(5, dtype = "float64")

array([0., 1., 2., 3., 4.])

In [134]:
np.arange(5.0, dtype = "int")

array([0, 1, 2, 3, 4])

In [139]:
np.arange(0, 5, 0.5, dtype = "int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [140]:
np.arange(0, 5, 1.5, dtype = int)

array([0, 1, 2, 3])

In [141]:
np.linspace(0, 1)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [142]:
np.linspace(0, 49)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49.])

In [143]:
np.linspace(0, 2, 3)

array([0., 1., 2.])

In [144]:
np.linspace(0, -2, 3)

array([ 0., -1., -2.])

In [145]:
np.linspace(0, 2, num = 3)

array([0., 1., 2.])

In [146]:
np.linspace(0, 2, num = 3, endpoint = False)

array([0.        , 0.66666667, 1.33333333])

In [148]:
np.linspace(0, 2, num = 3, endpoint = True)

array([0., 1., 2.])

In [150]:
np.linspace(0, 1, retstep = True)

(array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
        0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
        0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
        0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
        0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
        0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
        0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
        0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
        0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
        0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ]),
 0.02040816326530612)

In [151]:
np.linspace(0, 2, num = 3, retstep = True)

(array([0., 1., 2.]), 1.0)

In [152]:
np.linspace(0, 2, num = 3, retstep = False)

array([0., 1., 2.])

In [153]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [154]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [155]:
np.eye(2, 3)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [156]:
np.eye(5, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [157]:
np.eye(5, k = 0)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [158]:
np.eye(5, k = 1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [159]:
np.eye(5, k = -1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [168]:
np.eye(5, k = -4)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.]])

In [169]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [170]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [171]:
%timeit np.eye(10000)

13.9 ms ± 400 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [172]:
%timeit np.identity(10000)

13.6 ms ± 269 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [173]:
a = np.arange(10).reshape(2, 5)

In [174]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [175]:
b = a.flatten()

In [176]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [177]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [178]:
a.shape

(2, 5)

In [179]:
b.shape

(10,)

In [180]:
c = np.arange(12).reshape(2, 2, 3)

In [181]:
c

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [183]:
d = c.flatten()

In [184]:
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [185]:
c

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [187]:
c.shape

(2, 2, 3)

In [188]:
d.shape

(12,)

In [189]:
a = np.arange(10).reshape(2, 5)

In [190]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [192]:
a.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [193]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [194]:
np.ravel(a)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [195]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [197]:
a.ravel(order = "c")

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [198]:
a.ravel(order = "f")

array([0, 5, 1, 6, 2, 7, 3, 8, 4, 9])

In [199]:
b = np.arange(10).reshape(2, 5, order = "f")

In [200]:
b

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

In [201]:
b.ravel(order = "f")

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [202]:
b.ravel(order = "a")

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [203]:
b.ravel()

array([0, 2, 4, 6, 8, 1, 3, 5, 7, 9])

In [204]:
a = np.random.randint(0, 10, size = 20)

In [205]:
a

array([1, 7, 2, 1, 7, 4, 4, 2, 3, 5, 3, 7, 9, 5, 8, 0, 8, 8, 5, 5])

In [206]:
np.nonzero(a)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 16, 17,
        18, 19], dtype=int64),)

In [207]:
a.nonzero()

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 16, 17,
        18, 19], dtype=int64),)

In [208]:
a[np.nonzero(a)]

array([1, 7, 2, 1, 7, 4, 4, 2, 3, 5, 3, 7, 9, 5, 8, 8, 8, 5, 5])

In [209]:
np.where(a == 0)

(array([15], dtype=int64),)

In [210]:
a[np.where(a != 0)]

array([1, 7, 2, 1, 7, 4, 4, 2, 3, 5, 3, 7, 9, 5, 8, 8, 8, 5, 5])

In [211]:
b = np.random.randint(0, 10, size = (4, 5))

In [212]:
b

array([[6, 6, 0, 5, 9],
       [5, 4, 8, 9, 5],
       [9, 1, 8, 3, 0],
       [2, 9, 7, 1, 6]])

In [213]:
np.nonzero(b)

(array([0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 3], dtype=int64),
 array([0, 1, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 0, 1, 2, 3, 4], dtype=int64))

In [214]:
b.nonzero()

(array([0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 3], dtype=int64),
 array([0, 1, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 0, 1, 2, 3, 4], dtype=int64))

In [215]:
b[b.nonzero()]

array([6, 6, 5, 9, 5, 4, 8, 9, 5, 9, 1, 8, 3, 2, 9, 7, 1, 6])

In [216]:
b[np.where(b != 0)]

array([6, 6, 5, 9, 5, 4, 8, 9, 5, 9, 1, 8, 3, 2, 9, 7, 1, 6])

In [217]:
a = np.array([0, 1, 2])

In [218]:
np.tile(a, 1)

array([0, 1, 2])

In [219]:
np.tile(a, 2)

array([0, 1, 2, 0, 1, 2])

In [220]:
np.tile(a, (3, 2))

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

In [221]:
np.tile(a, (2, 3, 4))

array([[[0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2],
        [0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2],
        [0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2]],

       [[0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2],
        [0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2],
        [0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2]]])

In [222]:
np.newaxis is None

True

In [223]:
x = np.arange(15).reshape(3, 5)

In [224]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [225]:
x[np.newaxis, :, :]

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]])

In [226]:
x[:, np.newaxis, :]

array([[[ 0,  1,  2,  3,  4]],

       [[ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14]]])

In [227]:
x[:, None, :]

array([[[ 0,  1,  2,  3,  4]],

       [[ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14]]])

In [228]:
x[:, :, np.newaxis]

array([[[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4]],

       [[ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12],
        [13],
        [14]]])

In [229]:
x = x.flatten()

In [230]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [231]:
x[:, np.newaxis]

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14]])

In [232]:
x = np.arange(15).reshape(3, 5)

In [233]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [236]:
np.reshape(x, (1, 3, 5))

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]])

In [237]:
np.reshape(x, (3, 1, 5))

array([[[ 0,  1,  2,  3,  4]],

       [[ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14]]])

In [238]:
x = x.flatten()

In [239]:
np.reshape(x, (-1, 1))

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14]])