In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])

In [3]:
type(a)

numpy.ndarray

In [4]:
a

array([1, 2, 3])

In [5]:
a * 3

array([3, 6, 9])

In [6]:
a + 2

array([3, 4, 5])

In [7]:
[1, 2, 3] * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [8]:
b = np.array([2, 2, 0])

In [9]:
a + b

array([3, 4, 3])

In [10]:
a / b

<ipython-input-10-d8e10abd5ab6>:1: RuntimeWarning: divide by zero encountered in true_divide
  a / b


array([0.5, 1. , inf])

In [11]:
a * b

array([2, 4, 0])

In [12]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [14]:
np.linspace(0, 10, 15)

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

In [15]:
c = np.array([[1, 2, 3], [4, 5, 6]])

In [16]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
c.shape

(2, 3)

In [18]:
d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18], [19, 20, 21], [22, 23, 24]]])

In [19]:
d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [20]:
d.shape

(2, 4, 3)

In [21]:
c.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [22]:
c.reshape(6, 1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [23]:
import time

In [26]:
def calculate_time():
    a = np.random.randn(100000)
    b = list(a)
    start_time = time.time()
    for i in range(1000):
        sum_1 = np.sum(a)
    print("Using NumPy\t %f sec" % (time.time() - start_time))
    start_time = time.time()
    for i in range(1000):
        sum_2 = sum(b)
    print("Not using NumPy\t %f sec" % (time.time() - start_time))

In [27]:
calculate_time()

Using NumPy	 0.032007 sec
Not using NumPy	 4.768764 sec


In [28]:
import numpy as np

In [29]:
a = np.array([1, 2, 3])

In [30]:
type(a)

numpy.ndarray

In [31]:
a

array([1, 2, 3])

In [32]:
a.data

In [33]:
a.dtype

dtype('int32')

In [34]:
b = np.array([[1, 2, 3], [4, 5, 6]])

In [35]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
b.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [37]:
a.size

3

In [38]:
a.itemsize

4

In [39]:
a.nbytes

12

In [40]:
a.strides

(4,)

In [41]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [42]:
a.shape

(2, 3)

In [43]:
a.ndim

2

In [44]:
a = np.array([[0, 1], [2, 3], [4, 5]])

In [45]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [46]:
a.shape

(3, 2)

In [47]:
b = np.array([a, a])

In [48]:
b.shape

(2, 3, 2)

In [49]:
b

array([[[0, 1],
        [2, 3],
        [4, 5]],

       [[0, 1],
        [2, 3],
        [4, 5]]])

In [50]:
b.sum(axis = 0)

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [51]:
b.sum(axis = 1)

array([[6, 9],
       [6, 9]])

In [54]:
b.sum(axis = 2)

array([[1, 5, 9],
       [1, 5, 9]])

In [55]:
a = np.array([0, 1, 2])

In [56]:
a.dtype

dtype('int32')

In [57]:
b = np.array([0, 1, 2], dtype = "int64")

In [58]:
b.dtype

dtype('int64')

In [59]:
b

array([0, 1, 2], dtype=int64)

In [60]:
c = np.array([0, 1, 2], dtype = "float")

In [61]:
c

array([0., 1., 2.])

In [62]:
d = np.array([3e50, 4e35], dtype = "int64")

OverflowError: int too big to convert

In [63]:
d = np.array([3e50, 4e35], dtype = "float64")

In [64]:
d

array([3.e+50, 4.e+35])

In [65]:
e = np.array([3.5, 4.2, -4.3], dtype = "int")

In [66]:
e

array([ 3,  4, -4])

In [67]:
f = np.array([0, 2, 0, -1], dtype = "bool")

In [68]:
f

array([False,  True, False,  True])

In [69]:
a = [1, 2, 3, 4, 5]

In [70]:
a[1:-1]

[2, 3, 4]

In [71]:
a[1:]

[2, 3, 4, 5]

In [72]:
a = np.arange(10)

In [73]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
a[1:5]

array([1, 2, 3, 4])

In [75]:
a[2:8:2]

array([2, 4, 6])

In [76]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [77]:
a[:3]

array([0, 1, 2])

In [78]:
a[4:]

array([4, 5, 6, 7, 8, 9])

In [79]:
a[:3], a[3:]

(array([0, 1, 2]), array([3, 4, 5, 6, 7, 8, 9]))

In [80]:
a[::2]

array([0, 2, 4, 6, 8])

In [81]:
a[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
b = np.arange(20).reshape(4, 5)

In [83]:
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [84]:
b[1:3, 2:4]

array([[ 7,  8],
       [12, 13]])

In [85]:
b[:2, 1:]

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [86]:
b[::2, :]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14]])

In [87]:
b[:, ::2]

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14],
       [15, 17, 19]])

In [88]:
b[:, ::-1]

array([[ 4,  3,  2,  1,  0],
       [ 9,  8,  7,  6,  5],
       [14, 13, 12, 11, 10],
       [19, 18, 17, 16, 15]])

In [89]:
b[::-1, ::-1]

array([[19, 18, 17, 16, 15],
       [14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [90]:
a = np.array([[1, 2]])

In [91]:
a.shape

(1, 2)

In [92]:
b = np.array([3, 4])

In [93]:
b.shape

(2,)

In [94]:
a + b

array([[4, 6]])

In [95]:
a = np.array([1, 2, 3])

In [96]:
a.shape

(3,)

In [97]:
b = np.array([[1, 2], [3, 4], [5, 6]])

In [98]:
b.shape

(3, 2)

In [99]:
a + b

ValueError: operands could not be broadcast together with shapes (3,) (3,2) 

In [100]:
a = np.arange(12)

In [101]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [102]:
b = np.reshape(a, (3, 4))

In [103]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [104]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [105]:
b[0, 1] = 0

In [106]:
b

array([[ 0,  0,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [107]:
a

array([ 0,  0,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [108]:
c = np.arange(12)

In [109]:
d = np.reshape(c, (3, 4), order = "C")

In [110]:
d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [111]:
d = np.reshape(c, (3, 4), order = "F")

In [112]:
d

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [113]:
np.reshape(c, (3, 5))

ValueError: cannot reshape array of size 12 into shape (3,5)

In [114]:
a = np.arange(12)

In [115]:
np.reshape(a, (3, -1))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [116]:
np.reshape(a, (-1, 6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [117]:
a.reshape((3, -1))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [118]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [119]:
b = a.reshape((3, -1))

In [120]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [121]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [122]:
b[0, 0] = 1

In [123]:
b

array([[ 1,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [124]:
a

array([ 1,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [125]:
a = np.arange(12).reshape((3, 4))

In [126]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [127]:
b = np.arange(12).reshape((3, -1))

In [128]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [129]:
c = np.arange(15).reshape((3, 4))

ValueError: cannot reshape array of size 15 into shape (3,4)

In [130]:
a = np.arange(12)

In [131]:
np.reshape(a, (3, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [132]:
np.resize(a, (3, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11,  0,  1,  2]])

In [133]:
np.resize(a, (3, 2))

array([[0, 1],
       [2, 3],
       [4, 5]])

In [134]:
b = np.resize(a, (3, 4))

In [135]:
b[0, 1] = 0

In [136]:
b

array([[ 0,  0,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [137]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [138]:
a = np.arange(12)

In [139]:
np.append(a, [6, 4, 2])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  6,  4,  2])

In [140]:
b = np.arange(12).reshape((3, 4))

In [141]:
np.append(b, [1, 2, 3, 4])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  1,  2,  3,  4])

In [142]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [143]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [144]:
np.append(b, [[12, 13, 14, 15]])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [145]:
np.append(b, [[12, 13, 14, 15]], axis = 0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [146]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [147]:
np.append(b, [12, 13, 14, 15], axis = 0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [148]:
c = np.arange(12).reshape((3, 4))

In [149]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [150]:
d = np.linspace(0, 26, 12).reshape(3, 4)

In [151]:
d

array([[ 0.        ,  2.36363636,  4.72727273,  7.09090909],
       [ 9.45454545, 11.81818182, 14.18181818, 16.54545455],
       [18.90909091, 21.27272727, 23.63636364, 26.        ]])

In [152]:
np.append(c, d, axis = 0)

array([[ 0.        ,  1.        ,  2.        ,  3.        ],
       [ 4.        ,  5.        ,  6.        ,  7.        ],
       [ 8.        ,  9.        , 10.        , 11.        ],
       [ 0.        ,  2.36363636,  4.72727273,  7.09090909],
       [ 9.45454545, 11.81818182, 14.18181818, 16.54545455],
       [18.90909091, 21.27272727, 23.63636364, 26.        ]])

In [153]:
np.append(c, d, axis = 1)

array([[ 0.        ,  1.        ,  2.        ,  3.        ,  0.        ,
         2.36363636,  4.72727273,  7.09090909],
       [ 4.        ,  5.        ,  6.        ,  7.        ,  9.45454545,
        11.81818182, 14.18181818, 16.54545455],
       [ 8.        ,  9.        , 10.        , 11.        , 18.90909091,
        21.27272727, 23.63636364, 26.        ]])