In [1]:
import numpy as np

In [2]:
a = np.array([0, 1, 2, 3, 4])

In [3]:
b = np.array([2, 4, 6, 8, 10])

In [4]:
a + 4

array([4, 5, 6, 7, 8])

In [5]:
np.add(a, b)

array([ 2,  5,  8, 11, 14])

In [6]:
a + b

array([ 2,  5,  8, 11, 14])

In [7]:
np.add(a, 4)

array([4, 5, 6, 7, 8])

In [8]:
a - b

array([-2, -3, -4, -5, -6])

In [9]:
b - a

array([2, 3, 4, 5, 6])

In [10]:
a - 4

array([-4, -3, -2, -1,  0])

In [11]:
np.subtract(a, b)

array([-2, -3, -4, -5, -6])

In [12]:
np.subtract(b, a)

array([2, 3, 4, 5, 6])

In [13]:
np.subtract(a, 4)

array([-4, -3, -2, -1,  0])

In [14]:
a * b

array([ 0,  4, 12, 24, 40])

In [15]:
a * 2

array([0, 2, 4, 6, 8])

In [16]:
np.multiply(a, b)

array([ 0,  4, 12, 24, 40])

In [17]:
np.multiply(a, 2)

array([0, 2, 4, 6, 8])

In [18]:
b / a

<ipython-input-18-86f14ff2de04>:1: RuntimeWarning: divide by zero encountered in true_divide
  b / a


array([       inf, 4.        , 3.        , 2.66666667, 2.5       ])

In [19]:
b / 2

array([1., 2., 3., 4., 5.])

In [20]:
b / 3

array([0.66666667, 1.33333333, 2.        , 2.66666667, 3.33333333])

In [21]:
np.divide(b, a)

<ipython-input-21-3b08f6feaa81>:1: RuntimeWarning: divide by zero encountered in true_divide
  np.divide(b, a)


array([       inf, 4.        , 3.        , 2.66666667, 2.5       ])

In [22]:
np.divide(b, 2)

array([1., 2., 3., 4., 5.])

In [23]:
b // 3

array([0, 1, 2, 2, 3], dtype=int32)

In [24]:
b % 3

array([2, 1, 0, 2, 1], dtype=int32)

In [25]:
np.mod(b, 3)

array([2, 1, 0, 2, 1], dtype=int32)

In [26]:
np.power(2, 3)

8

In [27]:
2 ** 3

8

In [28]:
a = np.arange(1, 11, 1)

In [29]:
b = np.array([1, 2, 1, 2, 1, 2, 1, 2, 1, 2])

In [30]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
b

array([1, 2, 1, 2, 1, 2, 1, 2, 1, 2])

In [32]:
np.power(a, b)

array([  1,   4,   3,  16,   5,  36,   7,  64,   9, 100], dtype=int32)

In [33]:
a ** b

array([  1,   4,   3,  16,   5,  36,   7,  64,   9, 100], dtype=int32)

In [34]:
np.sqrt(2)

1.4142135623730951

In [35]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [36]:
np.sin(0)

0.0

In [37]:
np.cos(0)

1.0

In [38]:
np.tan(0)

0.0

In [39]:
np.sin(np.pi * 0.5)

1.0

In [40]:
np.cos(np.pi * 0.5)

6.123233995736766e-17

In [41]:
np.tan(np.pi * 0.5)

1.633123935319537e+16

In [42]:
np.arcsin(0.5)

0.5235987755982989

In [43]:
np.arccos(0.5)

1.0471975511965979

In [44]:
np.arctan(1)

0.7853981633974483

In [45]:
np.arcsin(-1)

-1.5707963267948966

In [46]:
np.arccos(-1)

3.141592653589793

In [47]:
np.arctan(-0.5)

-0.4636476090008061

In [48]:
np.deg2rad(120)

2.0943951023931953

In [49]:
np.rad2deg(3.141592653589793)

180.0

In [50]:
np.exp(1)

2.718281828459045

In [51]:
np.exp(2)

7.38905609893065

In [52]:
np.exp(0)

1.0

In [53]:
np.log(np.e)

1.0

In [54]:
a = np.array([1., 2., np.e ** 2, 10])

In [55]:
np.log(a)

array([0.        , 0.69314718, 2.        , 2.30258509])

In [56]:
b = np.array([1., 2., 4., 7])

In [57]:
np.log2(b)

array([0.        , 1.        , 2.        , 2.80735492])

In [58]:
c = np.array([1., 10., 20., 100.])

In [59]:
np.log10(c)

array([0.     , 1.     , 1.30103, 2.     ])

In [60]:
np.log1p(a)

array([0.69314718, 1.09861229, 2.12692801, 2.39789527])

In [61]:
np.log(2) / np.log(4)

0.5

In [62]:
np.log(9) / np.log(3)

2.0

In [63]:
np.sinh(2)

3.6268604078470186

In [64]:
np.cosh(2)

3.7621956910836314

In [65]:
np.tanh(2)

0.9640275800758169

In [66]:
np.arccosh(1)

0.0

In [67]:
np.arctanh(0.7)

0.8673005276940532

In [68]:
a = np.array([-1.8, -1.4, -1.0, -0.6, -0.2, 0., 0.2, 0.6, 1.0, 1.4, 1.0])

In [69]:
np.floor(a)

array([-2., -2., -1., -1., -1.,  0.,  0.,  0.,  1.,  1.,  1.])

In [70]:
np.trunc(a)

array([-1., -1., -1., -0., -0.,  0.,  0.,  0.,  1.,  1.,  1.])

In [71]:
np.ceil(a)

array([-1., -1., -1., -0., -0.,  0.,  1.,  1.,  1.,  2.,  1.])

In [72]:
np.round(a)

array([-2., -1., -1., -1., -0.,  0.,  0.,  1.,  1.,  1.,  1.])

In [73]:
np.around(a)

array([-2., -1., -1., -1., -0.,  0.,  0.,  1.,  1.,  1.,  1.])

In [74]:
np.rint(a)

array([-2., -1., -1., -1., -0.,  0.,  0.,  1.,  1.,  1.,  1.])

In [75]:
np.fix(a)

array([-1., -1., -1., -0., -0.,  0.,  0.,  0.,  1.,  1.,  1.])

In [76]:
a = -2.5

In [77]:
np.absolute(a)

2.5

In [78]:
np.fabs(a)

2.5

In [79]:
b = -2 + 3j

In [80]:
np.abs(b)

3.605551275463989

In [81]:
np.fabs(b)

TypeError: ufunc 'fabs' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [82]:
a = np.array([33, 44, 54, 23, 25, 55, 32, 76])

In [83]:
np.average(a)

42.75

In [84]:
a = a.reshape(2, 4)

In [85]:
a

array([[33, 44, 54, 23],
       [25, 55, 32, 76]])

In [86]:
np.average(a)

42.75

In [87]:
np.average(a, axis = 0)

array([29. , 49.5, 43. , 49.5])

In [88]:
np.average(a, axis = 1)

array([38.5, 47. ])

In [89]:
b = np.random.rand(24).reshape(2, 3, 4)

In [90]:
b

array([[[0.45005364, 0.46787194, 0.03093144, 0.07858611],
        [0.37975327, 0.91386702, 0.8745063 , 0.30820281],
        [0.8894136 , 0.70983851, 0.46752856, 0.211431  ]],

       [[0.53072393, 0.67745222, 0.57843398, 0.20775482],
        [0.55175827, 0.41733961, 0.05411712, 0.67878454],
        [0.81231234, 0.06675824, 0.61001431, 0.83560214]]])

In [91]:
np.average(b, axis = 0)

array([[0.49038878, 0.57266208, 0.30468271, 0.14317047],
       [0.46575577, 0.66560332, 0.46431171, 0.49349367],
       [0.85086297, 0.38829837, 0.53877144, 0.52351657]])

In [92]:
np.average(b, axis = 1)

array([[0.5730735 , 0.69719249, 0.45765543, 0.19940664],
       [0.63159818, 0.38718335, 0.41418847, 0.57404717]])

In [93]:
np.average(b, axis = 2)

array([[0.25686078, 0.61908235, 0.56955292],
       [0.49859124, 0.42549989, 0.58117176]])

In [94]:
a = a.flatten()

In [95]:
a

array([33, 44, 54, 23, 25, 55, 32, 76])

In [96]:
w = np.array([0.1, 0.05, 0.2, 0.0, 0.0, 0.4, 0.2, 0.05])

In [97]:
np.average(a, weights = w)

48.5

In [98]:
w2 = np.array([0.2, 0.8])

In [99]:
a = a.reshape(2, 4)

In [100]:
a

array([[33, 44, 54, 23],
       [25, 55, 32, 76]])

In [101]:
np.average(a, axis = 0, weights = w2)

array([26.6, 52.8, 36.4, 65.4])

In [102]:
np.average(a, returned = True)

(42.75, 8.0)

In [103]:
a = a.flatten()

In [104]:
w

array([0.1 , 0.05, 0.2 , 0.  , 0.  , 0.4 , 0.2 , 0.05])

In [105]:
np.average(a, weights = w, returned = True)

(48.5, 1.0)

In [106]:
a = np.random.randint(0, 10, 20)

In [107]:
a

array([5, 0, 3, 0, 7, 0, 5, 1, 3, 4, 9, 7, 6, 6, 1, 3, 3, 8, 7, 6])

In [108]:
np.mean(a)

4.2

In [109]:
a.mean()

4.2

In [110]:
b = a.reshape(4, 5)

In [111]:
b

array([[5, 0, 3, 0, 7],
       [0, 5, 1, 3, 4],
       [9, 7, 6, 6, 1],
       [3, 3, 8, 7, 6]])

In [112]:
np.mean(b)

4.2

In [113]:
b.mean()

4.2

In [114]:
np.mean(b, axis = 0)

array([4.25, 3.75, 4.5 , 4.  , 4.5 ])

In [115]:
np.mean(b, axis = 1)

array([3. , 2.6, 5.8, 5.4])

In [116]:
c = np.random.rand(2, 3, 4)

In [117]:
c

array([[[0.43386846, 0.06807533, 0.47461505, 0.96705463],
        [0.62838007, 0.08614323, 0.3342081 , 0.75277988],
        [0.78195281, 0.49656465, 0.38505469, 0.9906258 ]],

       [[0.91140388, 0.45055324, 0.27769142, 0.71138088],
        [0.04289117, 0.09760474, 0.18628008, 0.18935681],
        [0.02616891, 0.6927592 , 0.64612758, 0.52645468]]])

In [118]:
np.mean(c, axis = 0)

array([[0.67263617, 0.25931429, 0.37615324, 0.83921775],
       [0.33563562, 0.09187398, 0.26024409, 0.47106834],
       [0.40406086, 0.59466193, 0.51559113, 0.75854024]])

In [119]:
np.mean(c, axis = 1)

array([[0.61473378, 0.21692774, 0.39795928, 0.90348677],
       [0.32682132, 0.41363906, 0.37003303, 0.47573079]])

In [120]:
np.mean(c, axis = 2)

array([[0.48590337, 0.45037782, 0.66354949],
       [0.58775736, 0.1290332 , 0.47287759]])

In [121]:
b

array([[5, 0, 3, 0, 7],
       [0, 5, 1, 3, 4],
       [9, 7, 6, 6, 1],
       [3, 3, 8, 7, 6]])

In [122]:
e = np.mean(b, keepdims = True)

In [123]:
e

array([[4.2]])

In [124]:
e.shape

(1, 1)

In [125]:
f = np.mean(b, keepdims = False)

In [126]:
f

4.2

In [127]:
g = np.mean(b, axis = 1, keepdims = True)

In [128]:
g

array([[3. ],
       [2.6],
       [5.8],
       [5.4]])

In [129]:
g.shape

(4, 1)

In [130]:
h = np.mean(b, axis = 1, keepdims = False)

In [131]:
h

array([3. , 2.6, 5.8, 5.4])

In [132]:
h.shape

(4,)

In [133]:
a = np.random.randint(100, size = (2, 3, 4))

In [134]:
a

array([[[71, 10, 76,  7],
        [74, 16, 47, 87],
        [39, 79, 51,  8]],

       [[70, 35, 88, 66],
        [53, 27, 62, 23],
        [62,  9, 61, 73]]])

In [135]:
np.median(a)

57.0

In [136]:
np.median(a, axis = 2)

array([[40.5, 60.5, 45. ],
       [68. , 40. , 61.5]])

In [137]:
np.median(a, axis = 1)

array([[71., 16., 51.,  8.],
       [62., 27., 62., 66.]])

In [138]:
b = a.copy()

In [139]:
b

array([[[71, 10, 76,  7],
        [74, 16, 47, 87],
        [39, 79, 51,  8]],

       [[70, 35, 88, 66],
        [53, 27, 62, 23],
        [62,  9, 61, 73]]])

In [140]:
a

array([[[71, 10, 76,  7],
        [74, 16, 47, 87],
        [39, 79, 51,  8]],

       [[70, 35, 88, 66],
        [53, 27, 62, 23],
        [62,  9, 61, 73]]])

In [141]:
np.median(b, axis = 1, overwrite_input = True)

array([[71., 16., 51.,  8.],
       [62., 27., 62., 66.]])

In [142]:
np.all( a == b)

False

In [143]:
a

array([[[71, 10, 76,  7],
        [74, 16, 47, 87],
        [39, 79, 51,  8]],

       [[70, 35, 88, 66],
        [53, 27, 62, 23],
        [62,  9, 61, 73]]])

In [144]:
b

array([[[39, 10, 47,  7],
        [71, 16, 51,  8],
        [74, 79, 76, 87]],

       [[53,  9, 61, 23],
        [62, 27, 62, 66],
        [70, 35, 88, 73]]])

In [145]:
b = a.copy()

In [146]:
%timeit np.median(a, axis = 1)

22.5 µs ± 66.5 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [147]:
%timeit np.median(a, axis = 1, overwrite_input = True)

20 µs ± 64.3 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [148]:
np.median(a, axis = 0, keepdims = True)

array([[[46. ,  9.5, 54. , 15. ],
        [66.5, 21.5, 56.5, 37. ],
        [72. , 57. , 82. , 80. ]]])

In [149]:
np.median(a, axis = 1, keepdims =True)

array([[[71., 16., 51.,  8.]],

       [[62., 27., 62., 66.]]])

In [150]:
np.median(a, axis = 1, keepdims =False)

array([[71., 16., 51.,  8.],
       [62., 27., 62., 66.]])

In [152]:
a = np.random.randint(0, 10, size = (2, 5))

In [153]:
a

array([[7, 0, 6, 4, 9],
       [1, 5, 6, 3, 8]])

In [154]:
np.sum(a)

49

In [155]:
b = np.array([2, 4, 1, 6])

In [156]:
np.sum(b)

13

In [157]:
c = np.random.randint(0, 10, size = (2, 4, 5))

In [158]:
c

array([[[7, 8, 9, 6, 8],
        [0, 2, 6, 8, 9],
        [8, 0, 3, 8, 4],
        [0, 1, 7, 8, 5]],

       [[5, 3, 7, 2, 9],
        [9, 1, 5, 3, 6],
        [4, 1, 0, 2, 8],
        [2, 8, 7, 8, 5]]])

In [159]:
np.sum(c)

202

In [160]:
a

array([[7, 0, 6, 4, 9],
       [1, 5, 6, 3, 8]])

In [161]:
np.sum(a, axis = 0)

array([ 8,  5, 12,  7, 17])

In [162]:
np.sum(a, axis = 1)

array([26, 23])

In [163]:
c

array([[[7, 8, 9, 6, 8],
        [0, 2, 6, 8, 9],
        [8, 0, 3, 8, 4],
        [0, 1, 7, 8, 5]],

       [[5, 3, 7, 2, 9],
        [9, 1, 5, 3, 6],
        [4, 1, 0, 2, 8],
        [2, 8, 7, 8, 5]]])

In [164]:
np.sum(c, axis = 0)

array([[12, 11, 16,  8, 17],
       [ 9,  3, 11, 11, 15],
       [12,  1,  3, 10, 12],
       [ 2,  9, 14, 16, 10]])

In [165]:
np.sum(c, axis = 1)

array([[15, 11, 25, 30, 26],
       [20, 13, 19, 15, 28]])

In [166]:
np.sum(c, axis = 2)

array([[38, 25, 23, 21],
       [26, 24, 15, 30]])

In [167]:
np.sum(c, axis =0, keepdims =True)

array([[[12, 11, 16,  8, 17],
        [ 9,  3, 11, 11, 15],
        [12,  1,  3, 10, 12],
        [ 2,  9, 14, 16, 10]]])

In [168]:
np.sum(c, axis = 1, keepdims = True)

array([[[15, 11, 25, 30, 26]],

       [[20, 13, 19, 15, 28]]])

In [170]:
np.sum(c, axis = 2, keepdims = True)

array([[[38],
        [25],
        [23],
        [21]],

       [[26],
        [24],
        [15],
        [30]]])

In [177]:
a = np.random.rand(10000000)

In [178]:
np.std(a)

0.2886499239917034

In [179]:
b = np.random.rand(2, 3, 4)

In [180]:
b

array([[[0.75535576, 0.9357228 , 0.08505798, 0.4081349 ],
        [0.739375  , 0.14837952, 0.42617129, 0.21925694],
        [0.09878446, 0.61005269, 0.66513858, 0.19836017]],

       [[0.39213765, 0.38435107, 0.91250281, 0.2554332 ],
        [0.79226828, 0.88866443, 0.30889879, 0.35033033],
        [0.96653866, 0.19861415, 0.24966915, 0.72168532]]])

In [181]:
np.std(b, axis = 0)

array([[0.18160905, 0.27568586, 0.41372241, 0.07635085],
       [0.02644664, 0.37014246, 0.05863625, 0.06553669],
       [0.4338771 , 0.20571927, 0.20773472, 0.26166257]])

In [182]:
np.std(b)

0.2857319027815485

In [183]:
np.std(b, ddof = 1)

0.2918773779467004

In [184]:
a = np.array([10, 20, 12, 0, 3, 5])

In [185]:
np.var(a)

43.55555555555555