In [2]:
import numpy as np

In [4]:
a = np.array([[10, 5, 2, 4, 9, 3, 2], [10, 2, 8, 3, 7, 4, 1]])

In [5]:
np.cov(a)

array([[10.66666667,  6.66666667],
       [ 6.66666667, 11.33333333]])

In [6]:
c = np.array([3, 2, 1, 5, 7, 2, 1])

In [7]:
np.cov(a, c)

array([[10.66666667,  6.66666667,  4.66666667],
       [ 6.66666667, 11.33333333,  1.66666667],
       [ 4.66666667,  1.66666667,  5.        ]])

In [8]:
np.cov(a, bias = False)

array([[10.66666667,  6.66666667],
       [ 6.66666667, 11.33333333]])

In [9]:
np.cov(a, bias = True)

array([[9.14285714, 5.71428571],
       [5.71428571, 9.71428571]])

In [10]:
np.cov(a, ddof = None)

array([[10.66666667,  6.66666667],
       [ 6.66666667, 11.33333333]])

In [11]:
np.cov(a, ddof = 1)

array([[10.66666667,  6.66666667],
       [ 6.66666667, 11.33333333]])

In [12]:
np.cov(a, ddof = 0)

array([[9.14285714, 5.71428571],
       [5.71428571, 9.71428571]])

In [13]:
a

array([[10,  5,  2,  4,  9,  3,  2],
       [10,  2,  8,  3,  7,  4,  1]])

In [15]:
fweights = np.array([1, 2, 2, 1, 1, 1, 1])

In [16]:
np.cov(a, fweights = fweights)

array([[ 9.   ,  3.875],
       [ 3.875, 10.75 ]])

In [17]:
aweights = np.array([0.1, 0.2, 0.2, 0.2, 0.1, 0.1, 0.1])

In [18]:
np.cov(a, aweights = aweights)

array([[ 8.61904762,  3.83333333],
       [ 3.83333333, 10.66666667]])

In [19]:
np.cov(a, aweights = None)

array([[10.66666667,  6.66666667],
       [ 6.66666667, 11.33333333]])

In [20]:
x = np.array([[1, 2, 1, 9, 10, 3, 2, 6, 7], [2, 1, 8, 3, 7, 5, 10, 7, 2]])

In [21]:
np.corrcoef(x)

array([[ 1.        , -0.05640533],
       [-0.05640533,  1.        ]])

In [22]:
y = np.array([2, 1, 1, 8, 9, 4, 3, 5, 7])

In [24]:
np.corrcoef(x, y)

array([[ 1.        , -0.05640533,  0.97094584],
       [-0.05640533,  1.        , -0.01315587],
       [ 0.97094584, -0.01315587,  1.        ]])

In [25]:
np.corrcoef(x, rowvar = False)

array([[ 1., -1.,  1., -1., -1.,  1.,  1.,  1., -1.],
       [-1.,  1., -1.,  1.,  1., -1., -1., -1.,  1.],
       [ 1., -1.,  1., -1., -1.,  1.,  1.,  1., -1.],
       [-1.,  1., -1.,  1.,  1., -1., -1., -1.,  1.],
       [-1.,  1., -1.,  1.,  1., -1., -1., -1.,  1.],
       [ 1., -1.,  1., -1., -1.,  1.,  1.,  1., -1.],
       [ 1., -1.,  1., -1., -1.,  1.,  1.,  1., -1.],
       [ 1., -1.,  1., -1., -1.,  1.,  1.,  1., -1.],
       [-1.,  1., -1.,  1.,  1., -1., -1., -1.,  1.]])

In [26]:
x_transpose = x.T

In [27]:
np.corrcoef(x_transpose, rowvar = False)

array([[ 1.        , -0.05640533],
       [-0.05640533,  1.        ]])

In [29]:
np.corrcoef(x_transpose, rowvar = True)

array([[ 1., -1.,  1., -1., -1.,  1.,  1.,  1., -1.],
       [-1.,  1., -1.,  1.,  1., -1., -1., -1.,  1.],
       [ 1., -1.,  1., -1., -1.,  1.,  1.,  1., -1.],
       [-1.,  1., -1.,  1.,  1., -1., -1., -1.,  1.],
       [-1.,  1., -1.,  1.,  1., -1., -1., -1.,  1.],
       [ 1., -1.,  1., -1., -1.,  1.,  1.,  1., -1.],
       [ 1., -1.,  1., -1., -1.,  1.,  1.,  1., -1.],
       [ 1., -1.,  1., -1., -1.,  1.,  1.,  1., -1.],
       [-1.,  1., -1.,  1.,  1., -1., -1., -1.,  1.]])

In [30]:
a = np.array([0, 1, 2])

In [31]:
b = np.array([4, 0])

In [32]:
aa, bb = np.meshgrid(a, b)

In [33]:
aa

array([[0, 1, 2],
       [0, 1, 2]])

In [34]:
bb

array([[4, 4, 4],
       [0, 0, 0]])

In [35]:
aa2, bb2 = np.meshgrid(a, b, indexing = "xy")

In [36]:
aa2

array([[0, 1, 2],
       [0, 1, 2]])

In [37]:
bb2

array([[4, 4, 4],
       [0, 0, 0]])

In [39]:
aa3, bb3 = np.meshgrid(a, b, indexing = "ij")

In [40]:
aa3

array([[0, 0],
       [1, 1],
       [2, 2]])

In [41]:
bb3

array([[4, 0],
       [4, 0],
       [4, 0]])

In [42]:
av, bv = np.meshgrid(a, b, sparse = True)

In [44]:
av

array([[0, 1, 2]])

In [45]:
bv

array([[4],
       [0]])

In [46]:
a = np.array([1, 2])

In [48]:
b = np.array([4, 3])

In [49]:
np.dot(a, b)

10

In [50]:
np.dot(4, 5)

20

In [51]:
e = np.matrix([1, 2])

In [52]:
f = np.matrix([4, 3])

In [53]:
np.dot(e, f)

ValueError: shapes (1,2) and (1,2) not aligned: 2 (dim 1) != 1 (dim 0)

In [54]:
f = np.matrix([[4], [3]])

In [55]:
np.dot(e, f)

matrix([[10]])

In [58]:
a = np.array([[1, 2], [3, 4]])

In [59]:
b = ([[4, 3], [2, 1]])

In [60]:
np.dot(a, b)

array([[ 8,  5],
       [20, 13]])

In [61]:
np.dot(b, a)

array([[13, 20],
       [ 5,  8]])

In [64]:
c = np.arange(0, 9).reshape(3, 3)

In [66]:
d = np.ones((3, 3))

In [67]:
np.dot(c,d )

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

In [68]:
a = np.arange(12).reshape((4, 3))

In [69]:
b = np.arange(16).reshape((4, 4))

In [70]:
np.dot(a, b)

ValueError: shapes (4,3) and (4,4) not aligned: 3 (dim 1) != 4 (dim 0)

In [71]:
e = np.matrix([[0, 1, 2], [3, 4, 5], [6, 7, 8]])

In [73]:
f = np.matrix([[1, 1, 1], [1, 1, 1], [1, 1, 1]])

In [78]:
np.dot(d, e)

matrix([[ 9., 12., 15.],
        [ 9., 12., 15.],
        [ 9., 12., 15.]])

In [79]:
import numpy.linalg as LA

In [80]:
a = np.array([[2, 3], [4, -1]])

In [81]:
a

array([[ 2,  3],
       [ 4, -1]])

In [82]:
LA.det(a)

-14.000000000000004

In [83]:
d = np.random.randint(-5, 6, size = (3, 3, 3))

In [84]:
LA.det(d)

array([ 84., -17.,  19.])

In [85]:
a = np.array([[1, 0], [0, 2]])

In [86]:
a

array([[1, 0],
       [0, 2]])

In [87]:
LA.eig(a)

(array([1., 2.]),
 array([[1., 0.],
        [0., 1.]]))

In [88]:
b = np.array([[2, 5], [3, -8]])

In [89]:
b

array([[ 2,  5],
       [ 3, -8]])

In [90]:
LA.eig(b)

(array([ 3.32455532, -9.32455532]),
 array([[ 0.96665615, -0.40390206],
        [ 0.25607791,  0.91480224]]))

In [91]:
c = np.random.randint(-10, 10, size = (3, 3))

In [92]:
w, v = LA.eig(c)

In [93]:
w

array([-12.52480396+0.j        ,   0.26240198+3.67480774j,
         0.26240198-3.67480774j])

In [94]:
v

array([[-0.79966816+0.j        , -0.26294025-0.25570999j,
        -0.26294025+0.25570999j],
       [ 0.38334794+0.j        ,  0.7682915 +0.j        ,
         0.7682915 -0.j        ],
       [-0.46214196+0.j        ,  0.28587492+0.43986194j,
         0.28587492-0.43986194j]])

In [95]:
c = np.random.randint(-10, 10, size = (3, 3, 3))

In [96]:
w, v = LA.eig(c)

In [97]:
w

array([[ 9.92476056+0.j        , -1.96238028+1.76107139j,
        -1.96238028-1.76107139j],
       [-1.73951467+0.j        , -2.13024267+6.78608057j,
        -2.13024267-6.78608057j],
       [ 4.74028795+7.0661456j ,  4.74028795-7.0661456j ,
        -8.4805759 +0.j        ]])

In [100]:
v

array([[[ 0.64906269+0.j        , -0.90203617+0.j        ,
         -0.90203617-0.j        ],
        [ 0.49787646+0.j        ,  0.01468363+0.23686998j,
          0.01468363-0.23686998j],
        [ 0.57518402+0.j        ,  0.09933546-0.3466125j ,
          0.09933546+0.3466125j ]],

       [[-0.91627271+0.j        ,  0.1986361 -0.21573441j,
          0.1986361 +0.21573441j],
        [-0.02241674+0.j        ,  0.25522323-0.58016199j,
          0.25522323+0.58016199j],
        [-0.39992726+0.j        ,  0.71573426+0.j        ,
          0.71573426-0.j        ]],

       [[ 0.348406  -0.50568433j,  0.348406  +0.50568433j,
          0.28696434+0.j        ],
        [-0.029807  -0.09508042j, -0.029807  +0.09508042j,
          0.86501472+0.j        ],
        [ 0.78292265+0.j        ,  0.78292265-0.j        ,
          0.41158352+0.j        ]]])

In [101]:
A = np.array([[1, 1, 4, 0, 1], [0, 3, 1, 3, 2], [1, 3, 0, 0, 1], [2, 4, 3, 1, 1]])

In [102]:
LA.matrix_rank(A)

4

In [103]:
B = np.array([[1, 2, 3, 0], [2, 4, 6, 0], [1, 0, 1, 2], [1, 0, 0, 3]])

In [104]:
LA.matrix_rank(B)

3